<?php
// ─────────────────────────────────────────────
//  EastVille Comedy Club – Shared Data
// ─────────────────────────────────────────────

$shows = [
  [
    'id'          => 'show-1',
    'title'       => 'MONDAY NIGHT LIVE',
    'date'        => '2026-02-16T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$15',
    'priceValue'  => 15,
    'image'       => 'https://images.unsplash.com/photo-1649772308558-db37c0dfae7e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'description' => 'Start your week right with our Monday Night Live showcase! Featuring a rotating lineup of the city\'s best up-and-coming comedians and seasoned pros working on new material.',
    'lineup'      => ['Host: Sarah Johnson', 'Mike Smith', 'Jenny Jones', 'Special Guest'],
    'type'        => 'standup',
    'status'      => 'Tickets Available',
    'featured'    => true,
  ],
  [
    'id'          => 'show-2',
    'title'       => 'NEW TALENT TUESDAY',
    'date'        => '2026-02-17T19:30:00',
    'time'        => '07:30 PM',
    'location'    => 'Lounge',
    'price'       => '$10',
    'priceValue'  => 10,
    'image'       => 'https://images.unsplash.com/photo-1641903806973-17eaf2d2634f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'description' => 'Catch the rising stars of the New York comedy scene before they make it big.',
    'lineup'      => ['Host: Dave Miller', 'Various Artists'],
    'type'        => 'openmic',
    'status'      => 'Tickets Available',
    'featured'    => false,
  ],
  [
    'id'          => 'show-3',
    'title'       => 'HEADLINER SPECIAL: CHRIS ROCK',
    'date'        => '2026-02-18T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$45',
    'priceValue'  => 45,
    'image'       => 'https://images.unsplash.com/photo-1730791480843-12ef754c5123?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'description' => 'A rare intimate performance by one of the legends of comedy. Don\'t miss this opportunity to see Chris Rock live in Brooklyn.',
    'lineup'      => ['Chris Rock', 'Opener: Ali Wong'],
    'type'        => 'special',
    'status'      => 'Selling Fast',
    'featured'    => true,
  ],
  [
    'id'          => 'show-4',
    'title'       => 'IMPROV MADNESS',
    'date'        => '2026-02-19T19:00:00',
    'time'        => '07:00 PM',
    'location'    => 'Lounge',
    'price'       => '$20',
    'priceValue'  => 20,
    'image'       => 'https://images.unsplash.com/photo-1766360884068-b83757593c2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'description' => 'Everything is made up on the spot! Join our resident improv troupe for a chaotic and hilarious evening.',
    'lineup'      => ['The Brooklyn Improv Troupe'],
    'type'        => 'improv',
    'status'      => 'Tickets Available',
    'featured'    => true,
  ],
  [
    'id'          => 'show-5',
    'title'       => 'THURSDAY NIGHT THUNDER',
    'date'        => '2026-02-19T21:30:00',
    'time'        => '09:30 PM',
    'location'    => 'Main Stage',
    'price'       => '$25',
    'priceValue'  => 25,
    'image'       => 'https://images.unsplash.com/photo-1514525253440-b393452e8d26?auto=format&fit=crop&q=80&w=1080',
    'description' => 'Our signature Thursday night showcase featuring the best comedians from HBO, Netflix, and Comedy Central.',
    'lineup'      => ['Host: Mark Normand', 'Sam Morril', 'Jessica Kirson'],
    'type'        => 'standup',
    'status'      => 'Tickets Available',
    'featured'    => false,
  ],
  [
    'id'          => 'show-6',
    'title'       => 'FRIDAY NIGHT RAW',
    'date'        => '2026-02-20T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$30',
    'priceValue'  => 30,
    'image'       => 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=1080',
    'description' => 'Kick off the weekend with our raw and unfiltered Friday night showcase. No holds barred comedy.',
    'lineup'      => ['Host: Big Jay Oakerson', 'Dan Soder', 'Rosebud Baker'],
    'type'        => 'standup',
    'status'      => 'Selling Fast',
    'featured'    => true,
  ],
  [
    'id'          => 'show-7',
    'title'       => 'LATE NIGHT LAUGHS',
    'date'        => '2026-02-20T22:30:00',
    'time'        => '10:30 PM',
    'location'    => 'Main Stage',
    'price'       => '$25',
    'priceValue'  => 25,
    'image'       => 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1080',
    'description' => 'The darker side of comedy comes out late at night. Explicit content warning!',
    'lineup'      => ['Host: Ari Shaffir', 'Shane Gillis', 'Tim Dillon'],
    'type'        => 'standup',
    'status'      => 'Tickets Available',
    'featured'    => false,
  ],
  [
    'id'          => 'show-8',
    'title'       => 'SATURDAY MAIN EVENT',
    'date'        => '2026-02-21T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$35',
    'priceValue'  => 35,
    'image'       => 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=1080',
    'description' => 'Our premier Saturday night show. The perfect night out featuring top-tier talent.',
    'lineup'      => ['Host: Ronny Chieng', 'Hasan Minhaj', 'Michelle Wolf'],
    'type'        => 'standup',
    'status'      => 'Sold Out',
    'featured'    => true,
  ],
  [
    'id'          => 'show-9',
    'title'       => 'SUNDAY BRUNCH COMEDY',
    'date'        => '2026-02-22T14:00:00',
    'time'        => '02:00 PM',
    'location'    => 'Lounge',
    'price'       => '$20',
    'priceValue'  => 20,
    'image'       => 'https://images.unsplash.com/photo-1525268771113-32d9e9021a97?auto=format&fit=crop&q=80&w=1080',
    'description' => 'Mimosas and punchlines. The best way to cure a hangover.',
    'lineup'      => ['Host: Matteo Lane', 'Judy Gold'],
    'type'        => 'standup',
    'status'      => 'Tickets Available',
    'featured'    => false,
  ],
  [
    'id'          => 'show-10',
    'title'       => 'SUNDAY SHOWCASE',
    'date'        => '2026-02-22T19:00:00',
    'time'        => '07:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$20',
    'priceValue'  => 20,
    'image'       => 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&q=80&w=1080',
    'description' => 'Wrap up the weekend with a relaxed but hilarious lineup.',
    'lineup'      => ['Host: Joe List', 'Mark Normand'],
    'type'        => 'standup',
    'status'      => 'Tickets Available',
    'featured'    => false,
  ],
  [
    'id'          => 'show-11',
    'title'       => 'CROWD WORK SPECIAL',
    'date'        => '2026-02-23T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Lounge',
    'price'       => '$20',
    'priceValue'  => 20,
    'image'       => 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&q=80&w=1080',
    'description' => 'No prepared jokes, just pure interaction with the audience. Anything can happen!',
    'lineup'      => ['Host: Stavros Halkias'],
    'type'        => 'special',
    'status'      => 'Tickets Available',
    'featured'    => true,
  ],
  [
    'id'          => 'show-12',
    'title'       => 'MARCH MADNESS OPEN MIC',
    'date'        => '2026-03-02T19:30:00',
    'time'        => '07:30 PM',
    'location'    => 'Lounge',
    'price'       => '$10',
    'priceValue'  => 10,
    'image'       => 'https://images.unsplash.com/photo-1641903806973-17eaf2d2634f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'description' => 'Kick off the month with new jokes and fresh faces at our famous open mic.',
    'lineup'      => ['Host: Kevin Hart (Maybe)', 'You?'],
    'type'        => 'openmic',
    'status'      => 'Tickets Available',
    'featured'    => false,
  ],
  [
    'id'          => 'show-13',
    'title'       => 'WOMEN OF COMEDY',
    'date'        => '2026-03-04T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$25',
    'priceValue'  => 25,
    'image'       => 'https://images.unsplash.com/photo-1514525253440-b393452e8d26?auto=format&fit=crop&q=80&w=1080',
    'description' => 'Celebrating the funniest women in the business. A night of non-stop laughter.',
    'lineup'      => ['Host: Whitney Cummings', 'Taylor Tomlinson', 'Iliza Shlesinger'],
    'type'        => 'standup',
    'status'      => 'Selling Fast',
    'featured'    => true,
  ],
  [
    'id'          => 'show-14',
    'title'       => 'FRIDAY NIGHT RAW: MARCH EDITION',
    'date'        => '2026-03-06T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$30',
    'priceValue'  => 30,
    'image'       => 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=1080',
    'description' => 'The rawest show in town continues into March.',
    'lineup'      => ['Host: Big Jay Oakerson', 'Guest Comedians'],
    'type'        => 'standup',
    'status'      => 'Tickets Available',
    'featured'    => false,
  ],
  [
    'id'          => 'show-15',
    'title'       => 'SATURDAY STAR POWER',
    'date'        => '2026-03-07T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$40',
    'priceValue'  => 40,
    'image'       => 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=1080',
    'description' => 'You never know who will drop in on a Saturday night in March!',
    'lineup'      => ['Surprise Headliner', 'Regular Favorites'],
    'type'        => 'standup',
    'status'      => 'Selling Fast',
    'featured'    => true,
  ],
  [
    'id'          => 'show-16',
    'title'       => 'ST. PATRICK\'S PRE-GAME',
    'date'        => '2026-03-14T20:00:00',
    'time'        => '08:00 PM',
    'location'    => 'Main Stage',
    'price'       => '$35',
    'priceValue'  => 35,
    'image'       => 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1080',
    'description' => 'Get your green on early and laugh until you cry.',
    'lineup'      => ['Host: Colin Quinn', 'Irish Comedians'],
    'type'        => 'special',
    'status'      => 'Tickets Available',
    'featured'    => true,
  ],
];

// ─────────────────────────────────────────────
//  Helper: format date parts from ISO string
// ─────────────────────────────────────────────
function formatShowDate(string $isoDate): array {
  $ts = strtotime($isoDate);
  return [
    'weekday' => date('D', $ts),
    'day'     => date('j', $ts),
    'month'   => date('M', $ts),
    'year'    => date('Y', $ts),
    'time'    => date('g:i A', $ts),
  ];
}
